{% set name = "meteora" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/meteora-{{ version }}.tar.gz
  sha256: 82dc4ffab806bcf18c9bfe0d53c6bab209678ee9fce728d8dc2571a287566179

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - setuptools >=61.0
    - pip
  run:
    - python >=3.10
    - dask
    - geopandas >=1.0.0
    - matplotlib-base
    - osmnx >=2.0.0
    - polars
    - pooch
    - pyarrow
    - requests
    - requests-cache
    - requests-oauthlib
    - seaborn
    - statsmodels
    - tqdm
    - xarray
    - xvec

test:
  imports:
    - meteora
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/martibosch/meteora
  summary: Pythonic interface to access data from meteorological stations
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE

extra:
  recipe-maintainers:
    - martibosch
