{% set name = "meteora" %}
{% set version = "0.7.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/meteora-{{ version }}.tar.gz
  sha256: 98d6166ce656d78faee0ea23d7f202eabdd4d8f326f8182fb7d02f5b7bcf5f5b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - pip
  run:
    - python >={{ python_min }}
    - dask
    - geopandas >=1.0.0
    - matplotlib-base
    - osmnx >=2.0.0
    - pooch
    - requests
    - requests-cache
    - requests-oauthlib
    - seaborn
    - statsmodels
    - tqdm
    - xarray
    - xvec

test:
  imports:
    - meteora
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/martibosch/meteora
  summary: Pythonic interface to access data from meteorological stations
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE

extra:
  recipe-maintainers:
    - martibosch
